# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created: Sun Mar  6 01:37:11 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Wizard(object):
    def setupUi(self, Wizard):
        Wizard.setObjectName(_fromUtf8("Wizard"))
        Wizard.resize(712, 430)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.label_4 = QtGui.QLabel(self.wizardPage1)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 200, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 177, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.wizardPage1)
        self.label_5.setGeometry(QtCore.QRect(297, 36, 59, 21))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label = QtGui.QLabel(self.wizardPage1)
        self.label.setGeometry(QtCore.QRect(9, 36, 128, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_6 = QtGui.QLabel(self.wizardPage1)
        self.label_6.setGeometry(QtCore.QRect(300, 100, 388, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setGeometry(QtCore.QRect(270, 0, 130, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.name = QtGui.QLineEdit(self.wizardPage1)
        self.name.setGeometry(QtCore.QRect(9, 63, 251, 31))
        self.name.setObjectName(_fromUtf8("name"))
        self.email = QtGui.QLineEdit(self.wizardPage1)
        self.email.setGeometry(QtCore.QRect(10, 140, 251, 31))
        self.email.setObjectName(_fromUtf8("email"))
        self.phoneNumber = QtGui.QLineEdit(self.wizardPage1)
        self.phoneNumber.setGeometry(QtCore.QRect(10, 210, 251, 31))
        self.phoneNumber.setObjectName(_fromUtf8("phoneNumber"))
        self.websites = QtGui.QPlainTextEdit(self.wizardPage1)
        self.websites.setGeometry(QtCore.QRect(300, 130, 371, 131))
        self.websites.setObjectName(_fromUtf8("websites"))
        self.address = QtGui.QLineEdit(self.wizardPage1)
        self.address.setGeometry(QtCore.QRect(300, 60, 371, 31))
        self.address.setObjectName(_fromUtf8("address"))
        Wizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.widget = QtGui.QWidget(self.wizardPage2)
        self.widget.setGeometry(QtCore.QRect(9, 36, 681, 321))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(10, 170, 121, 21))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gpa1 = QtGui.QDoubleSpinBox(self.widget)
        self.gpa1.setGeometry(QtCore.QRect(10, 200, 62, 31))
        self.gpa1.setObjectName(_fromUtf8("gpa1"))
        self.label_11 = QtGui.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(370, 10, 231, 21))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(370, 90, 301, 21))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.school1 = QtGui.QLineEdit(self.widget)
        self.school1.setGeometry(QtCore.QRect(12, 40, 271, 31))
        self.school1.setObjectName(_fromUtf8("school1"))
        self.major1 = QtGui.QLineEdit(self.widget)
        self.major1.setGeometry(QtCore.QRect(10, 130, 271, 31))
        self.major1.setObjectName(_fromUtf8("major1"))
        self.schoolStart1 = QtGui.QLineEdit(self.widget)
        self.schoolStart1.setGeometry(QtCore.QRect(370, 40, 271, 31))
        self.schoolStart1.setObjectName(_fromUtf8("schoolStart1"))
        self.endSchool1 = QtGui.QLineEdit(self.widget)
        self.endSchool1.setGeometry(QtCore.QRect(370, 130, 271, 31))
        self.endSchool1.setObjectName(_fromUtf8("endSchool1"))
        self.label_7 = QtGui.QLabel(self.wizardPage2)
        self.label_7.setGeometry(QtCore.QRect(280, 0, 68, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        Wizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName(_fromUtf8("wizardPage3"))
        self.widget_2 = QtGui.QWidget(self.wizardPage3)
        self.widget_2.setGeometry(QtCore.QRect(10, 40, 681, 321))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_13 = QtGui.QLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 251, 21))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 191, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_16 = QtGui.QLabel(self.widget_2)
        self.label_16.setGeometry(QtCore.QRect(370, 10, 231, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.widget_2)
        self.label_17.setGeometry(QtCore.QRect(370, 90, 301, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.orgName1 = QtGui.QLineEdit(self.widget_2)
        self.orgName1.setGeometry(QtCore.QRect(12, 40, 271, 31))
        self.orgName1.setObjectName(_fromUtf8("orgName1"))
        self.jobTitle1 = QtGui.QLineEdit(self.widget_2)
        self.jobTitle1.setGeometry(QtCore.QRect(10, 130, 271, 31))
        self.jobTitle1.setObjectName(_fromUtf8("jobTitle1"))
        self.jobStart1 = QtGui.QLineEdit(self.widget_2)
        self.jobStart1.setGeometry(QtCore.QRect(370, 40, 271, 31))
        self.jobStart1.setObjectName(_fromUtf8("jobStart1"))
        self.jobEnd1 = QtGui.QLineEdit(self.widget_2)
        self.jobEnd1.setGeometry(QtCore.QRect(370, 130, 271, 31))
        self.jobEnd1.setObjectName(_fromUtf8("jobEnd1"))
        self.jobDesc1 = QtGui.QPlainTextEdit(self.widget_2)
        self.jobDesc1.setGeometry(QtCore.QRect(10, 200, 471, 71))
        self.jobDesc1.setObjectName(_fromUtf8("jobDesc1"))
        self.label_15 = QtGui.QLabel(self.widget_2)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 461, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_18 = QtGui.QLabel(self.wizardPage3)
        self.label_18.setGeometry(QtCore.QRect(270, 10, 131, 21))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        Wizard.addPage(self.wizardPage3)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.label_19 = QtGui.QLabel(self.wizardPage)
        self.label_19.setGeometry(QtCore.QRect(280, 0, 171, 21))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.widget_3 = QtGui.QWidget(self.wizardPage)
        self.widget_3.setGeometry(QtCore.QRect(10, 30, 681, 331))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.personalDev1 = QtGui.QPlainTextEdit(self.widget_3)
        self.personalDev1.setGeometry(QtCore.QRect(20, 40, 631, 281))
        self.personalDev1.setObjectName(_fromUtf8("personalDev1"))
        self.label_20 = QtGui.QLabel(self.widget_3)
        self.label_20.setGeometry(QtCore.QRect(20, 10, 621, 21))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        Wizard.addPage(self.wizardPage)
        self.wizardPage_2 = QtGui.QWizardPage()
        self.wizardPage_2.setObjectName(_fromUtf8("wizardPage_2"))
        self.label_21 = QtGui.QLabel(self.wizardPage_2)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 271, 21))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.strongSkills = QtGui.QPlainTextEdit(self.wizardPage_2)
        self.strongSkills.setGeometry(QtCore.QRect(10, 60, 331, 131))
        self.strongSkills.setObjectName(_fromUtf8("strongSkills"))
        self.label_22 = QtGui.QLabel(self.wizardPage_2)
        self.label_22.setGeometry(QtCore.QRect(260, 0, 181, 21))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.wizardPage_2)
        self.label_23.setGeometry(QtCore.QRect(10, 200, 341, 21))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.strongTech = QtGui.QPlainTextEdit(self.wizardPage_2)
        self.strongTech.setGeometry(QtCore.QRect(10, 230, 331, 111))
        self.strongTech.setObjectName(_fromUtf8("strongTech"))
        self.label_24 = QtGui.QLabel(self.wizardPage_2)
        self.label_24.setGeometry(QtCore.QRect(370, 30, 331, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_25 = QtGui.QLabel(self.wizardPage_2)
        self.label_25.setGeometry(QtCore.QRect(370, 50, 331, 21))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.wizardPage_2)
        self.label_26.setGeometry(QtCore.QRect(370, 70, 331, 21))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.wizardPage_2)
        self.label_27.setGeometry(QtCore.QRect(370, 90, 331, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.altSkills = QtGui.QPlainTextEdit(self.wizardPage_2)
        self.altSkills.setGeometry(QtCore.QRect(370, 120, 311, 221))
        self.altSkills.setObjectName(_fromUtf8("altSkills"))
        Wizard.addPage(self.wizardPage_2)
        self.wizardPage_3 = QtGui.QWizardPage()
        self.wizardPage_3.setObjectName(_fromUtf8("wizardPage_3"))
        self.label_28 = QtGui.QLabel(self.wizardPage_3)
        self.label_28.setGeometry(QtCore.QRect(250, 0, 211, 21))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(self.wizardPage_3)
        self.label_29.setGeometry(QtCore.QRect(10, 30, 261, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.achievements = QtGui.QTextEdit(self.wizardPage_3)
        self.achievements.setGeometry(QtCore.QRect(10, 70, 331, 281))
        self.achievements.setObjectName(_fromUtf8("achievements"))
        self.label_30 = QtGui.QLabel(self.wizardPage_3)
        self.label_30.setGeometry(QtCore.QRect(360, 30, 291, 21))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.references = QtGui.QPlainTextEdit(self.wizardPage_3)
        self.references.setGeometry(QtCore.QRect(360, 70, 321, 281))
        self.references.setObjectName(_fromUtf8("references"))
        Wizard.addPage(self.wizardPage_3)
        self.wizardPage_4 = QtGui.QWizardPage()
        self.wizardPage_4.setObjectName(_fromUtf8("wizardPage_4"))
        self.label_31 = QtGui.QLabel(self.wizardPage_4)
        self.label_31.setGeometry(QtCore.QRect(300, 0, 64, 21))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.wizardPage_4)
        self.label_32.setGeometry(QtCore.QRect(20, 30, 651, 21))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.kurllabel = KUrlLabel(self.wizardPage_4)
        self.kurllabel.setGeometry(QtCore.QRect(20, 50, 631, 21))
        self.kurllabel.setObjectName(_fromUtf8("kurllabel"))
        self.objective = QtGui.QPlainTextEdit(self.wizardPage_4)
        self.objective.setGeometry(QtCore.QRect(20, 90, 651, 271))
        self.objective.setObjectName(_fromUtf8("objective"))
        Wizard.addPage(self.wizardPage_4)
        self.wizardPage_5 = QtGui.QWizardPage()
        self.wizardPage_5.setObjectName(_fromUtf8("wizardPage_5"))
        self.label_34 = QtGui.QLabel(self.wizardPage_5)
        self.label_34.setGeometry(QtCore.QRect(20, 10, 651, 31))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.wizardPage_5)
        self.label_35.setGeometry(QtCore.QRect(20, 40, 651, 31))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_36 = QtGui.QLabel(self.wizardPage_5)
        self.label_36.setGeometry(QtCore.QRect(20, 90, 651, 31))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.wizardPage_5)
        self.label_37.setGeometry(QtCore.QRect(20, 120, 651, 31))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_38 = QtGui.QLabel(self.wizardPage_5)
        self.label_38.setGeometry(QtCore.QRect(20, 150, 651, 31))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_39 = QtGui.QLabel(self.wizardPage_5)
        self.label_39.setGeometry(QtCore.QRect(20, 180, 651, 31))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_40 = QtGui.QLabel(self.wizardPage_5)
        self.label_40.setGeometry(QtCore.QRect(20, 290, 651, 31))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.pushButton = QtGui.QPushButton(self.wizardPage_5)
        self.pushButton.setGeometry(QtCore.QRect(500, 320, 131, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_41 = QtGui.QLabel(self.wizardPage_5)
        self.label_41.setGeometry(QtCore.QRect(20, 230, 651, 31))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.wizardPage_5)
        self.label_42.setGeometry(QtCore.QRect(20, 260, 651, 31))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        Wizard.addPage(self.wizardPage_5)
        self.wizardPage_6 = QtGui.QWizardPage()
        self.wizardPage_6.setObjectName(_fromUtf8("wizardPage_6"))
        Wizard.addPage(self.wizardPage_6)

        self.retranslateUi(Wizard)
        QtCore.QMetaObject.connectSlotsByName(Wizard)

    def retranslateUi(self, Wizard):
        Wizard.setWindowTitle(_translate("Wizard", "Rart", None))
        self.label_4.setText(_translate("Wizard", "Phone number to contact you?", None))
        self.label_3.setText(_translate("Wizard", "Professional contact email?", None))
        self.label_5.setText(_translate("Wizard", "Address?", None))
        self.label.setText(_translate("Wizard", "What is your name?", None))
        self.label_6.setText(_translate("Wizard", "Do you have any websites? Github? Anything else relevant?", None))
        self.label_2.setText(_translate("Wizard", "Contact Information", None))
        self.label_8.setText(_translate("Wizard", "What school did you attend?", None))
        self.label_9.setText(_translate("Wizard", "What is your major?", None))
        self.label_10.setText(_translate("Wizard", "GPA? (Optional)", None))
        self.label_11.setText(_translate("Wizard", "When did you start? (Month YYYY)", None))
        self.label_12.setText(_translate("Wizard", "Graduate? Leave empty if still attending", None))
        self.label_7.setText(_translate("Wizard", "Academics", None))
        self.label_13.setText(_translate("Wizard", "What is the name of the organization?", None))
        self.label_14.setText(_translate("Wizard", "What was your job title?", None))
        self.label_16.setText(_translate("Wizard", "When did you start? (Month YYYY)", None))
        self.label_17.setText(_translate("Wizard", "When did you leave? (empty if still working)", None))
        self.label_15.setText(_translate("Wizard", "Give a brief description of your job. Include skills and achievements!", None))
        self.label_18.setText(_translate("Wizard", "Work Experience", None))
        self.label_19.setText(_translate("Wizard", "Personal Development", None))
        self.label_20.setText(_translate("Wizard", "Write about some of your projects! Talk about skills you used and what you learned.", None))
        self.label_21.setText(_translate("Wizard", "What are some of your strongest skills?", None))
        self.label_22.setText(_translate("Wizard", "Skills and Technologies", None))
        self.label_23.setText(_translate("Wizard", "What are some technologies you are familiar with?", None))
        self.label_24.setText(_translate("Wizard", "List any other skills or technologies that you", None))
        self.label_25.setText(_translate("Wizard", "have experience with but didn\'t want to list on", None))
        self.label_26.setText(_translate("Wizard", "your main resume. This is the first step to building", None))
        self.label_27.setText(_translate("Wizard", "your smart resume!", None))
        self.label_28.setText(_translate("Wizard", "Achievements and references", None))
        self.label_29.setText(_translate("Wizard", "What are some of your achievements?", None))
        self.label_30.setText(_translate("Wizard", "List some of your references", None))
        self.label_31.setText(_translate("Wizard", "Objective", None))
        self.label_32.setText(_translate("Wizard", "This is a place to write your objective. Click the link below for some tips to write a good objective!", None))
        self.kurllabel.setText(_translate("Wizard", "<html><head/><body><p><a href=\"https://resumegenius.com/how-to-write-a-resume/career-objective-writing-guide\"><span style=\" text-decoration: underline; color:#0000ff;\">Objective Help!</span></a></p></body></html>", None))
        self.label_34.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">Great job! You\'re almost done. Before you hit make resume, make</span></p></body></html>", None))
        self.label_35.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">sure there\'s no typos and everything is correct and up to date.</span></p></body></html>", None))
        self.label_36.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">When you\'re done hit the button below and all you\'re info will be</span></p></body></html>", None))
        self.label_37.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">put into a .docx file in a nice premade format! Use our format or </span></p></body></html>", None))
        self.label_38.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">give it your own personal flair! Check out our website for a </span></p></body></html>", None))
        self.label_39.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">step-by-step guide and resources to help build your resume.</span></p></body></html>", None))
        self.label_40.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">Good luck!</span></p></body></html>", None))
        self.pushButton.setText(_translate("Wizard", "Make resume", None))
        self.label_41.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">If you want to make your resume relevant to a specific job, go to</span></p></body></html>", None))
        self.label_42.setText(_translate("Wizard", "<html><head/><body><p><span style=\" font-size:16pt;\">the next page.</span></p></body></html>", None))

from PyKDE4.kdeui import KUrlLabel
